version: "3.8"

networks:
  dev_network:

services:

  relay-db:
    container_name: relay-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: rushmi0
      POSTGRES_PASSWORD: sql@min
      POSTGRES_DB: nostr
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      - dev_network
    ports:
      - "5432:5432"

  relay-cache:
    container_name: relay-cache
    image: redis:7.0-alpine
    restart: unless-stopped
    networks:
      - dev_network
    ports:
      - "6379:6379"

  relay-app:
    container_name: relay-app
    image: amazoncorretto:21.0.3
    restart: unless-stopped
    volumes:
      - .:/app/source-code
    working_dir: /app/source-code
    command: >
      /bin/bash -c "chmod +x run_jvm.sh; ./run_jvm.sh"
    ports:
      - "6724:6724"
    networks:
      - dev_network


  cloudflared-tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token

