version: "3.9"

networks:
  dev_network:

services:

  relay-db:
    container_name: relay-postgres
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "54330:5432"
    environment:
      POSTGRES_PASSWORD: sql@min
    volumes:
      - ./src/main/resources/db/sql:/docker-entrypoint-initdb.d/
    networks:
      - dev_network