version: "3.9"

networks:
  dev_network:

services:

  relay-db:
    container_name: relay-postgres
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "54330:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sql@min
      POSTGRES_DB: nostr
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d/
    networks:
      - dev_network

  redis:
    container_name: relay-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - dev_network

